config/routes.rb
Rails.application.routes.draw do

  namespace :module do
    namespace :performer_manage do
      resources :tender_comments
    end
  end
  namespace :module,path: 'admin' do
    get '/:nick' => 'admin#show',as: 'admin_show'
    namespace :admin_manage,path: 'manage' do
      resources :categories
    end

  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/home'
  get 'home/contacts'
  get 'tender/show_tender_info'
  get 'tender/show_contacts/:id' => 'tender#show_contacts',as: 'tender_show_contacts'

  namespace :module,path: 'performer' do
    get '/:nick' => 'performer#show', as: 'performer_show'

  end

  namespace :module,path: 'customer' do
    get '/:nick' => 'customer#show', as: 'customer_show'
    namespace :customer_manage,path: 'manage' do
      resources :tenders
    end
  end

  get 'cabinet' =>'cabinet#set_cabinet_url',as: 'cabinet'

  get 'geo_json_tender' => 'geojson#get_tenders', as: 'tenders_in_geo_json'

  root 'home#index'

end

app/models/module/performer_manage/tender_comment.rb
class Module::PerformerManage::TenderComment
  include Mongoid::Document
end

app/controllers/module/performer_manage/tender_comments_controller.rb
class Module::PerformerManage::TenderCommentsController < ApplicationController
  before_action :set_module_performer_manage_tender_comment, only: [:show, :edit, :update, :destroy]

  # GET /module/performer_manage/tender_comments
  # GET /module/performer_manage/tender_comments.json
  def index
    @tender_comments = Module::PerformerManage::TenderComment.all
  end

  # GET /module/performer_manage/tender_comments/1
  # GET /module/performer_manage/tender_comments/1.json
  def show
  end

  # GET /module/performer_manage/tender_comments/new
  def new
    @tender_comment = Module::PerformerManage::TenderComment.new
  end

  # GET /module/performer_manage/tender_comments/1/edit
  def edit
  end

  # POST /module/performer_manage/tender_comments
  # POST /module/performer_manage/tender_comments.json
  def create
    @tender_comment = Module::PerformerManage::TenderComment.new(module_performer_manage_tender_comment_params)

    respond_to do |format|
      if @tender_comment.save
        format.html { redirect_to @tender_comment, notice: 'Tender comment was successfully created.' }
        format.json { render :show, status: :created, location: @tender_comment }
      else
        format.html { render :new }
        format.json { render json: @tender_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /module/performer_manage/tender_comments/1
  # PATCH/PUT /module/performer_manage/tender_comments/1.json
  def update
    respond_to do |format|
      if @tender_comment.update(module_performer_manage_tender_comment_params)
        format.html { redirect_to @tender_comment, notice: 'Tender comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @tender_comment }
      else
        format.html { render :edit }
        format.json { render json: @tender_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /module/performer_manage/tender_comments/1
  # DELETE /module/performer_manage/tender_comments/1.json
  def destroy
    @tender_comment.destroy
    respond_to do |format|
      format.html { redirect_to module_performer_manage_tender_comments_url, notice: 'Tender comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_module_performer_manage_tender_comment
      @tender_comment = Module::PerformerManage::TenderComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def module_performer_manage_tender_comment_params
      params.fetch(:tender_comment, {})
    end
end

app/helpers/module/performer_manage/tender_comments_helper.rb
module Module::PerformerManage::TenderCommentsHelper
end

app/views/module/performer_manage/tender_comments/_form.html.haml
= form_for @tender_comment do |f|
  - if @tender_comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tender_comment.errors.count, "error")} prohibited this module_performer_manage_tender_comment from being saved:"
      %ul
        - @tender_comment.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/module/performer_manage/tender_comments/edit.html.haml
%h1 Editing module_performer_manage_tender_comment

= render 'form'

= link_to 'Show', @tender_comment
\|
= link_to 'Back', module_performer_manage_tender_comments_path

app/views/module/performer_manage/tender_comments/index.html.haml
%h1 Listing module_performer_manage_tender_comments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @tender_comments.each do |module_performer_manage_tender_comment|
      %tr
        %td= link_to 'Show', module_performer_manage_tender_comment
        %td= link_to 'Edit', edit_module_performer_manage_tender_comment_path(module_performer_manage_tender_comment)
        %td= link_to 'Destroy', module_performer_manage_tender_comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tender comment', new_module_performer_manage_tender_comment_path

app/views/module/performer_manage/tender_comments/new.html.haml
%h1 New module_performer_manage_tender_comment

= render 'form'

= link_to 'Back', module_performer_manage_tender_comments_path

app/views/module/performer_manage/tender_comments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_module_performer_manage_tender_comment_path(@tender_comment)
\|
= link_to 'Back', module_performer_manage_tender_comments_path