config/routes.rb
Rails.application.routes.draw do

  namespace :module do
    namespace :performer_manage do
      resources :tender_comments
    end
  end
  namespace :module,path: 'admin' do
    get '/:nick' => 'admin#show',as: 'admin_show'
    namespace :admin_manage,path: 'manage' do
      resources :categories
    end

  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/home'
  get 'home/contacts'
  get 'tender/show_tender_info'
  get 'tender/show_contacts/:id' => 'tender#show_contacts',as: 'tender_show_contacts'

  namespace :module,path: 'performer' do
    get '/:nick' => 'performer#show', as: 'performer_show'

  end

  namespace :module,path: 'customer' do
    get '/:nick' => 'customer#show', as: 'customer_show'
    namespace :customer_manage,path: 'manage' do
      resources :tenders
    end
  end

  get 'cabinet' =>'cabinet#set_cabinet_url',as: 'cabinet'

  get 'geo_json_tender' => 'geojson#get_tenders', as: 'tenders_in_geo_json'

  root 'home#index'

end

app/models/module/customer_manage/tender.rb
class Module::CustomerManage::Tender
  include Mongoid::Document
  include Mongoid::Timestamps
  include ::Geocoder::Model::Mongoid

  field :title,type: String
  field :description,type: String
  field :budget,type: Integer
  field :address, type: String
  field :contact_data, type: String
  field :finish_at, type: Date
  field :coordinates,type: Array

  embeds_many :reviews, class_name: 'User'
  belongs_to :author,class_name: 'User'
  belongs_to :category,class_name: 'Module::AdminManage::Category'
  scope :get_by_author, -> (user){where(author: user)}

  validates :title,:description,:author,:category, presence: true
  validates :budget,numericality: {only_integer: true}

  before_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def geocode
    self.coordinates =  Geocoder.coordinates(address)
  end
end

app/models/tender.rb
class Tender
  include Mongoid::Document

  field :title,type: String
  field :description,type: String
  field :budget,type: Integer
  field :address, type: String

  belongs_to :author,class_name: 'User'

  scope :get_by_author, -> (user){where(author: user)}

  validates :title,:description,:author, presence: true
  validates :budget,numericality: {only_integer: true}

end

app/controllers/module/customer_manage/tenders_controller.rb
class Module::CustomerManage::TendersController < Module::ApplicationController
  respond_to :html

  before_action :set_customer_tender,only:[:show,:update,:edit]

  def index
    @tenders = Module::CustomerManage::Tender.get_by_author(current_user).page(params[:page]).per(PAGINATE_PER_PAGE)
  end

  def new
    @customer_tender = Module::CustomerManage::Tender.new
  end

  def create
    @customer_tender = Module::CustomerManage::Tender.new(customer_tender_params)
    @customer_tender.author = current_user
    if @customer_tender.save
      flash[:notice] = 'Тендер було збережено'
    end
    respond_with(@customer_tender)
  end

  def edit
  end

  def show
  end

  def update
    @customer_tender.update(customer_tender_params)
    respond_with(@customer_tender)
  end

  private

  def set_customer_tender
    @customer_tender = Module::CustomerManage::Tender.find(params[:id])
  end

  def customer_tender_params
    params.require(:module_customer_manage_tender).permit(:category,:address,:title, :description, :contact_data, :budget)
  end


end

app/controllers/tender_controller.rb
class TenderController < ApplicationController
  layout false
  before_action :authenticate_user!, except: [:show_tender_info]

  def show_contacts
    @tender = Module::CustomerManage::Tender.find(params[:id])
    @tender.reviews << current_user
    @tender.save
  end

  def show_tender_info
    @tender = Module::CustomerManage::Tender.find(params[:id])
    respond_with(@tender)
  end
end

app/helpers/tender_helper.rb
module TenderHelper
end

app/views/module/customer_manage/tenders/_form.html.haml
:scss
  fieldset{
    //background: white;
  }

.col-md-8
  =bootstrap_form_for @customer_tender, :html => { :class => 'form-vertical' } do |f|
    %fieldset
      = f.text_field :title,label: 'Назва тендеру'
      = f.text_area :description,label: 'Опис'
      = f.text_field :address, label: 'Адреса'
      = f.select :category, Module::AdminManage::Category.all.map{ |cat| [ cat.title,cat.id ] } , label: 'Категорія'
      = f.text_field :contact_data,label: 'Контактні дані'
      = f.number_field :budget,label: 'Приблизний бюджет'
      = f.submit 'Зберегти'

app/views/module/customer_manage/tenders/edit.html.haml
.col-xs-12
  %h2
    Редагування тендеру
.col-xs-12
  =link_to 'Мої тендери',module_customer_manage_tenders_path,class: 'btn btn-primary'
  =link_to 'Переглянути',module_customer_manage_tender_path(@customer_tender),class: 'btn btn-primary'
.col-xs-12
  =render 'form'

app/views/module/customer_manage/tenders/index.html.haml
:scss
  .bold-font{
    font-weight: bold;
    margin-bottom: 15px;
    text-align: center;
  }
.col-md-12
  %h2
    Перегляд усіх Ваших тендерів
  =link_to 'Створити тендер',new_module_customer_manage_tender_path,class: 'btn btn-primary'
  -unless @tenders.empty?
    .row.bold-font
      .col-md-3
        Назва
      .col-md-6
        Опис
      .col-md-3.text-center
        Дії
    -@tenders.each do |tender|
      .row
        .col-md-3
          =tender.title
        .col-md-6
          =tender.description
        .col-md-3.action_button.text-center
          = link_to image_tag('crud_icons/loupe.png'),module_customer_manage_tender_path(tender)
          = link_to image_tag('crud_icons/pencil.png'),edit_module_customer_manage_tender_path(tender)
          = link_to image_tag('crud_icons/X_icon.png'),module_customer_manage_tender_path(tender),method: :delete
  -else
    Ще не створено жодного тендеру
= paginate @tenders

app/views/module/customer_manage/tenders/new.html.haml
.col-xs-12
  %h2
    Створення нового тендеру
.col-xs-12
  =link_to 'Мої тендери',module_customer_manage_tenders_path,class: 'btn btn-primary'
.col-xs-12
  =render 'form'

app/views/module/customer_manage/tenders/show.html.haml
=link_to 'Мої тендери',module_customer_manage_tenders_path,class: 'btn btn-primary'

%p
  =@customer_tender.author.nick_name
%p
  =@customer_tender.category.title
%p
  =@customer_tender.address
%p
  =@customer_tender.budget
%p
  =@customer_tender.contact_data
%p
  =@customer_tender.coordinates