config/routes.rb
Rails.application.routes.draw do

  namespace :module do
    namespace :performer_manage do
      resources :tender_comments
    end
  end
  namespace :module,path: 'admin' do
    get '/:nick' => 'admin#show',as: 'admin_show'
    namespace :admin_manage,path: 'manage' do
      resources :categories
    end

  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/home'
  get 'home/contacts'
  get 'tender/show_tender_info'
  get 'tender/show_contacts/:id' => 'tender#show_contacts',as: 'tender_show_contacts'

  namespace :module,path: 'performer' do
    get '/:nick' => 'performer#show', as: 'performer_show'

  end

  namespace :module,path: 'customer' do
    get '/:nick' => 'customer#show', as: 'customer_show'
    namespace :customer_manage,path: 'manage' do
      resources :tenders
    end
  end

  get 'cabinet' =>'cabinet#set_cabinet_url',as: 'cabinet'

  get 'geo_json_tender' => 'geojson#get_tenders', as: 'tenders_in_geo_json'

  root 'home#index'

end

app/models/module/admin_manage/category.rb
require 'carrierwave/mongoid'
class Module::AdminManage::Category
  include Mongoid::Document
  has_many :subordinates,class_name: 'Module::AdminManage::Category',foreign_key: "p_id"

  scope :get_parent_categories, -> {where(p_id: nil)}
  field :title, type: String
  field :p_id, type: String
  field :alias,type: String
  mount_uploader :img, TenderCategoriesUploader

  skip_callback :update, :before, :store_previous_model_for_img
  validates_presence_of :img
  validates :alias, uniqueness: true,allow_blank: true
  validates :title, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title,:p_id,:alias)
    end
end

app/controllers/module/admin_manage/categories_controller.rb
class Module::AdminManage::CategoriesController < Module::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :get_parents_category,only: [:new,:edit]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Module::AdminManage::Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Module::AdminManage::Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Module::AdminManage::Category.new(category_params)
    binding.pry
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to module_admin_manage_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_parents_category
      @parent_categories = Module::AdminManage::Category.get_parent_categories
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Module::AdminManage::Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:module_admin_manage_category).permit(:title,:p_id,:alias,:img)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/module/admin_manage/categories/_form.html.haml
= bootstrap_form_for @category do |f|
  = f.select :p_id,@parent_categories.map { |p_cat|[p_cat.title,p_cat.id]  },label: 'Виберіть категорію',prompt: 'Категорії'
  = f.text_field :alias,label: 'Аліас категорії'
  = f.text_field :title,label: 'Назва категорії'
  = f.file_field :img, label: 'Картинка'
  = f.submit 'Зберегти'

:javascript
  $(document).ready(function(){
    $('#module_admin_manage_category_p_id').change(function() {
      var alias_input_dom = $('#module_admin_manage_category_alias').parents('.form-group')
      if($(this).val()){
        alias_input_dom.hide('slow');
      }else{
        alias_input_dom.show('slow');
      }
    })
    $('form').submit(function(){
      if($('#module_admin_manage_category_p_id').val()){
        $('#module_admin_manage_category_alias').val('');
      }
    })
  });

app/views/module/admin_manage/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Переглянути', @category
\|
= link_to 'Категорії', module_admin_manage_categories_path

app/views/module/admin_manage/categories/index.html.haml
%h1 Усі категорії
= link_to 'Нова категорія', new_module_admin_manage_category_path,class: 'btn btn-default'
%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.title
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_module_admin_manage_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/module/admin_manage/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Категорії', module_admin_manage_categories_path

app/views/module/admin_manage/categories/show.html.haml
%p#notice= notice

.row
  %p
    = "Назва: #{@category.title}"
  .col-md-2
    = image_tag(@category.img.url,class: 'img-responsive category-img')
= link_to 'Редагувати', edit_module_admin_manage_category_path(@category)
\|
= link_to 'Категорії', module_admin_manage_categories_path